{
    "spec_evidence": "src/backend/tests/unit/test_interview_prep_prompt_context.py",
    "generated_at": "20260306T082812Z",
    "result": "pass",
    "note": "Generated by RECOVERY_008 closure",
}
