"""Tests for scripts/spec_quality/check_evidence_integrity.py."""

from __future__ import annotations

import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[4]
SCRIPT_PATH = REPO_ROOT / 'scripts' / 'spec_quality' / 'check_evidence_integrity.py'


def _run(*args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(SCRIPT_PATH), *args],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )


def test_aggregate_mode_passes_with_fresh_complete_evidence(tmp_path: Path) -> None:
    yaml2_dir = tmp_path / 'yaml2'
    evidence_dir = tmp_path / 'evidence'
    yaml2_dir.mkdir()
    evidence_dir.mkdir()

    (yaml2_dir / 'sample.yaml').write_text(
        '\n'.join(
            [
                'spec_id: SAMPLE_001',
                'status: validated',
                'traceability_matrix:',
                '  - requirement_id: AC-SAMPLE-001',
                '    evidence_reference: docs/evidence/sample-evidence-20260306T000000Z.json',
                '    result: pass',
            ]
        ),
        encoding='utf-8',
    )

    payload = {
        'spec_id': 'SAMPLE_001',
        'requirement_id': 'AC-SAMPLE-001',
        'git_sha': '4f29ab8',
        'deployment_id': 'dep-001',
        'environment': 'dev',
        'executed_at_utc': datetime.now(timezone.utc).isoformat().replace('+00:00', 'Z'),
    }
    (evidence_dir / 'sample-evidence-20260306T000000Z.json').write_text(
        json.dumps(payload),
        encoding='utf-8',
    )

    result = _run(
        '--yaml2-dir',
        str(yaml2_dir),
        '--evidence-dir',
        str(evidence_dir),
    )

    assert result.returncode == 0, result.stderr
    report = json.loads(result.stdout)
    assert report['status'] == 'pass'
    assert report['issues'] == []


def test_aggregate_mode_fails_placeholder_and_missing_fields(tmp_path: Path) -> None:
    yaml2_dir = tmp_path / 'yaml2'
    evidence_dir = tmp_path / 'evidence'
    yaml2_dir.mkdir()
    evidence_dir.mkdir()

    (yaml2_dir / 'sample.yaml').write_text(
        '\n'.join(
            [
                'spec_id: SAMPLE_002',
                'status: validated',
                'traceability_matrix:',
                '  - requirement_id: AC-SAMPLE-002',
                '    evidence_reference: docs/evidence/sample-fail-20260306T000000Z.json',
                '    result: pass',
            ]
        ),
        encoding='utf-8',
    )

    (evidence_dir / 'sample-fail-20260306T000000Z.json').write_text(
        json.dumps(
            {
                'spec_id': 'SAMPLE_002',
                'requirement_id': 'AC-SAMPLE-002',
                'note': 'Generated by RECOVERY_008 closure placeholder',
            }
        ),
        encoding='utf-8',
    )

    result = _run(
        '--yaml2-dir',
        str(yaml2_dir),
        '--evidence-dir',
        str(evidence_dir),
    )

    assert result.returncode == 1
    report = json.loads(result.stdout)
    assert report['status'] == 'fail'
    assert any('missing fields' in issue for issue in report['issues'])


def test_spec_mode_backwards_compatible(tmp_path: Path) -> None:
    artifacts_dir = tmp_path / 'artifacts'
    artifacts_dir.mkdir()
    spec_path = tmp_path / 'step.yaml'

    spec_path.write_text(
        '\n'.join(
            [
                'spec_id: RECOVERY_X',
                'traceability_matrix:',
                '  - requirement_id: AC-X-001',
                '    evidence_reference: docs/evidence/ac-x-<timestamp>.json',
            ]
        ),
        encoding='utf-8',
    )

    artifact_payload = {
        'spec_id': 'RECOVERY_X',
        'requirement_id': 'AC-X-001',
        'git_sha': '4f29ab8',
        'executed_at_utc': datetime.now(timezone.utc).isoformat().replace('+00:00', 'Z'),
    }
    (artifacts_dir / 'ac-x-20260306T000000Z.json').write_text(
        json.dumps(artifact_payload),
        encoding='utf-8',
    )

    result = _run(
        '--spec',
        str(spec_path),
        '--artifacts-dir',
        str(artifacts_dir),
    )

    assert result.returncode == 0, result.stderr
    report = json.loads(result.stdout)
    assert report['status'] == 'pass'
