#!/usr/bin/env python3
"""Validate evidence integrity for a single spec or for the full yaml2 closure set."""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

try:
    import yaml  # type: ignore[import-untyped]
except Exception as exc:  # pragma: no cover
    print(f"ERROR: PyYAML is required: {exc}", file=sys.stderr)
    raise SystemExit(2)


PASS_STATUSES = {"validated", "closed"}
GIT_SHA_RE = re.compile(r"^[0-9a-fA-F]{7,40}$")
PLACEHOLDER_MARKERS = (
    "<timestamp>",
    "placeholder",
    "todo",
    "tbd",
    "generated by recovery_008 closure",
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Verify evidence artifacts are present and contain required integrity fields."
        )
    )
    parser.add_argument(
        "--spec", help="Path to step_*.yaml spec (legacy per-spec mode)"
    )
    parser.add_argument(
        "--artifacts-dir",
        help="Evidence artifact directory for per-spec mode, usually docs/evidence",
    )
    parser.add_argument(
        "--evidence-dir",
        help=(
            "Aggregate mode: evidence directory used with yaml2 sweep "
            "(for example docs/evidence)"
        ),
    )
    parser.add_argument(
        "--yaml2-dir",
        default="docs/beta/fix-api/yaml2",
        help="Aggregate mode: directory containing yaml2 specs",
    )
    parser.add_argument(
        "--required-environment",
        default="dev",
        help="Aggregate mode: expected environment value in evidence payloads",
    )
    parser.add_argument(
        "--max-age-days",
        type=int,
        default=14,
        help="Aggregate mode: max allowed age for executed_at_utc evidence timestamps",
    )
    parser.add_argument(
        "--require-deployment-id-for",
        action="append",
        default=[],
        help="Per-spec mode: blocking gate names that require deployment_id",
    )
    parser.add_argument("--out", help="Optional JSON report output path")
    args = parser.parse_args()

    if args.spec:
        if not args.artifacts_dir:
            parser.error("--artifacts-dir is required when --spec is provided")
    else:
        if not args.evidence_dir:
            parser.error("either --spec/--artifacts-dir or --evidence-dir is required")
    return args


def _split_evidence_reference(value: str) -> list[str]:
    # Supports values like: "file-a-<timestamp>.json and file-b-<timestamp>.json"
    parts = [p.strip() for p in value.split(" and ")]
    return [p for p in parts if p]


def _reference_to_glob(reference: str) -> str:
    return Path(reference).name.replace("<timestamp>", "*")


def _json_load(path: Path) -> tuple[dict[str, Any] | None, str | None]:
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:
        return None, str(exc)
    if not isinstance(raw, dict):
        return None, "artifact root must be a JSON object"
    return raw, None


def _contains_placeholder(value: Any) -> bool:
    try:
        text = json.dumps(value, sort_keys=True).lower()
    except Exception:
        text = str(value).lower()
    return any(marker in text for marker in PLACEHOLDER_MARKERS)


def _parse_timestamp(value: str) -> datetime | None:
    normalized = value.strip()
    if not normalized:
        return None
    if normalized.endswith("Z"):
        normalized = normalized[:-1] + "+00:00"
    try:
        parsed = datetime.fromisoformat(normalized)
    except ValueError:
        return None
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc)


def _validate_spec_mode(
    payload: dict[str, Any],
    *,
    spec_id: str,
    requirement_id: str,
    required_fields: list[str],
    artifact_name: str,
) -> list[str]:
    issues: list[str] = []
    missing = [
        field for field in required_fields if payload.get(field) in (None, "", [])
    ]
    if missing:
        issues.append(
            f"{requirement_id}: {artifact_name} missing fields: {', '.join(missing)}"
        )
    if payload.get("spec_id") and payload.get("spec_id") != spec_id:
        issues.append(
            f"{requirement_id}: {artifact_name} spec_id mismatch "
            f"(expected {spec_id}, got {payload.get('spec_id')})"
        )
    if (
        payload.get("requirement_id")
        and payload.get("requirement_id") != requirement_id
    ):
        issues.append(
            f"{requirement_id}: {artifact_name} requirement_id mismatch "
            f"(got {payload.get('requirement_id')})"
        )
    return issues


def _validate_aggregate_mode(
    payload: dict[str, Any],
    *,
    spec_id: str,
    requirement_id: str,
    required_environment: str,
    max_age_days: int,
    artifact_name: str,
) -> list[str]:
    issues: list[str] = []
    required_fields = [
        "spec_id",
        "requirement_id",
        "git_sha",
        "deployment_id",
        "environment",
        "executed_at_utc",
    ]
    missing = [
        field for field in required_fields if payload.get(field) in (None, "", [])
    ]
    if missing:
        issues.append(
            f"{requirement_id}: {artifact_name} missing fields: {', '.join(missing)}"
        )
        return issues

    if payload.get("spec_id") != spec_id:
        issues.append(
            f"{requirement_id}: {artifact_name} spec_id mismatch "
            f"(expected {spec_id}, got {payload.get('spec_id')})"
        )
    if payload.get("requirement_id") != requirement_id:
        issues.append(
            f"{requirement_id}: {artifact_name} requirement_id mismatch "
            f"(expected {requirement_id}, got {payload.get('requirement_id')})"
        )

    git_sha = str(payload.get("git_sha", "")).strip()
    if not GIT_SHA_RE.fullmatch(git_sha):
        issues.append(
            f"{requirement_id}: {artifact_name} git_sha is not a valid short/full SHA"
        )

    environment = str(payload.get("environment", "")).strip().lower()
    if environment != required_environment.lower():
        issues.append(
            f"{requirement_id}: {artifact_name} environment mismatch "
            f"(expected {required_environment}, got {payload.get('environment')})"
        )

    executed = _parse_timestamp(str(payload.get("executed_at_utc", "")))
    if executed is None:
        issues.append(
            f"{requirement_id}: {artifact_name} executed_at_utc is not ISO-8601 UTC"
        )
    else:
        oldest_allowed = datetime.now(timezone.utc) - timedelta(days=max_age_days)
        if executed < oldest_allowed:
            issues.append(
                f"{requirement_id}: {artifact_name} evidence is stale "
                f"(executed_at_utc={payload.get('executed_at_utc')}, max_age_days={max_age_days})"
            )

    if _contains_placeholder(payload):
        issues.append(f"{requirement_id}: {artifact_name} contains placeholder markers")

    return issues


def _run_spec_mode(args: argparse.Namespace) -> tuple[int, dict[str, object]]:
    spec_path = Path(args.spec)
    artifacts_dir = Path(args.artifacts_dir)
    required_deployment_gates = set(args.require_deployment_id_for)
    issues: list[str] = []
    checked_files: list[str] = []

    if not spec_path.exists():
        print(f"ERROR: spec missing: {spec_path}", file=sys.stderr)
        return 2, {}
    if not artifacts_dir.exists():
        print(f"ERROR: artifacts dir missing: {artifacts_dir}", file=sys.stderr)
        return 2, {}

    spec = yaml.safe_load(spec_path.read_text(encoding="utf-8"))
    spec_id = str(spec.get("spec_id", "")).strip()
    if not spec_id:
        issues.append("spec missing spec_id")

    traceability = spec.get("traceability_matrix") or []
    if not isinstance(traceability, list) or not traceability:
        issues.append("traceability_matrix missing or empty")

    for item in traceability:
        if not isinstance(item, dict):
            issues.append("invalid traceability entry type")
            continue
        requirement_id = str(item.get("requirement_id", "")).strip()
        blocking_gate = str(item.get("blocking_gate", "")).strip()
        evidence_reference = str(item.get("evidence_reference", "")).strip()
        if not requirement_id:
            issues.append("traceability entry missing requirement_id")
            continue
        if not evidence_reference:
            issues.append(f"{requirement_id}: missing evidence_reference")
            continue

        refs = _split_evidence_reference(evidence_reference)
        if not refs:
            issues.append(f"{requirement_id}: unable to parse evidence_reference")
            continue

        matched_any = False
        for ref in refs:
            glob_pattern = _reference_to_glob(ref)
            matches = sorted(artifacts_dir.glob(glob_pattern))
            if not matches:
                issues.append(f"{requirement_id}: no artifact matches {glob_pattern}")
                continue
            matched_any = True
            for artifact in matches:
                checked_files.append(str(artifact))
                payload, parse_error = _json_load(artifact)
                if payload is None:
                    issues.append(
                        f"{requirement_id}: invalid JSON artifact {artifact.name}: {parse_error}"
                    )
                    continue
                required_fields = [
                    "spec_id",
                    "requirement_id",
                    "git_sha",
                    "executed_at_utc",
                ]
                if blocking_gate in required_deployment_gates:
                    required_fields.append("deployment_id")
                issues.extend(
                    _validate_spec_mode(
                        payload,
                        spec_id=spec_id,
                        requirement_id=requirement_id,
                        required_fields=required_fields,
                        artifact_name=artifact.name,
                    )
                )
        if not matched_any:
            issues.append(f"{requirement_id}: no evidence artifacts resolved")

    report = {
        "mode": "spec",
        "spec": str(spec_path),
        "artifacts_dir": str(artifacts_dir),
        "checked_file_count": len(set(checked_files)),
        "issues": issues,
        "status": "pass" if not issues else "fail",
    }
    return (0 if not issues else 1), report


def _run_aggregate_mode(args: argparse.Namespace) -> tuple[int, dict[str, object]]:
    yaml2_dir = Path(args.yaml2_dir)
    evidence_dir = Path(args.evidence_dir)
    issues: list[str] = []
    checked_files: list[str] = []

    if not yaml2_dir.exists():
        print(f"ERROR: yaml2 dir missing: {yaml2_dir}", file=sys.stderr)
        return 2, {}
    if not evidence_dir.exists():
        print(f"ERROR: evidence dir missing: {evidence_dir}", file=sys.stderr)
        return 2, {}

    yaml_files = sorted(yaml2_dir.glob("*.yaml"))
    if not yaml_files:
        issues.append("no yaml2 specs found")

    for spec_path in yaml_files:
        try:
            spec = yaml.safe_load(spec_path.read_text(encoding="utf-8"))
        except Exception as exc:
            issues.append(f"{spec_path.name}: YAML parse error: {exc}")
            continue

        spec_id = str(spec.get("spec_id", spec_path.stem)).strip()
        status = str(spec.get("status", "")).strip().lower()
        if status not in PASS_STATUSES:
            issues.append(
                f"{spec_id}: status must be one of {sorted(PASS_STATUSES)}, got '{status or 'missing'}'"
            )

        traceability = spec.get("traceability_matrix") or []
        if not isinstance(traceability, list) or not traceability:
            issues.append(f"{spec_id}: traceability_matrix missing or empty")
            continue

        for item in traceability:
            if not isinstance(item, dict):
                issues.append(f"{spec_id}: invalid traceability entry type")
                continue

            requirement_id = str(item.get("requirement_id", "")).strip()
            result = str(item.get("result", "")).strip().lower()
            evidence_reference = str(item.get("evidence_reference", "")).strip()
            if not requirement_id:
                issues.append(f"{spec_id}: traceability item missing requirement_id")
                continue
            if result != "pass":
                issues.append(
                    f"{spec_id}:{requirement_id}: result is '{result or 'missing'}'"
                )
            if not evidence_reference:
                issues.append(f"{spec_id}:{requirement_id}: missing evidence_reference")
                continue
            if not evidence_reference.startswith("docs/evidence/"):
                issues.append(
                    f"{spec_id}:{requirement_id}: evidence_reference must point to docs/evidence/*"
                )

            refs = _split_evidence_reference(evidence_reference)
            if not refs:
                issues.append(
                    f"{spec_id}:{requirement_id}: unable to parse evidence_reference"
                )
                continue

            resolved_any = False
            for ref in refs:
                glob_pattern = _reference_to_glob(ref)
                matches = sorted(evidence_dir.glob(glob_pattern))
                if not matches:
                    issues.append(
                        f"{spec_id}:{requirement_id}: no artifact matches {glob_pattern}"
                    )
                    continue
                resolved_any = True
                for artifact in matches:
                    checked_files.append(str(artifact))
                    payload, parse_error = _json_load(artifact)
                    if payload is None:
                        issues.append(
                            f"{spec_id}:{requirement_id}: invalid JSON artifact "
                            f"{artifact.name}: {parse_error}"
                        )
                        continue
                    issues.extend(
                        _validate_aggregate_mode(
                            payload,
                            spec_id=spec_id,
                            requirement_id=requirement_id,
                            required_environment=args.required_environment,
                            max_age_days=args.max_age_days,
                            artifact_name=artifact.name,
                        )
                    )
            if not resolved_any:
                issues.append(
                    f"{spec_id}:{requirement_id}: no evidence artifacts resolved"
                )

    report = {
        "mode": "aggregate",
        "yaml2_dir": str(yaml2_dir),
        "evidence_dir": str(evidence_dir),
        "required_environment": args.required_environment,
        "max_age_days": args.max_age_days,
        "checked_file_count": len(set(checked_files)),
        "issues": issues,
        "status": "pass" if not issues else "fail",
    }
    return (0 if not issues else 1), report


def main() -> int:
    args = parse_args()
    if args.spec:
        exit_code, report = _run_spec_mode(args)
    else:
        exit_code, report = _run_aggregate_mode(args)

    if report:
        if args.out:
            out_path = Path(args.out)
            out_path.parent.mkdir(parents=True, exist_ok=True)
            out_path.write_text(json.dumps(report, indent=2), encoding="utf-8")
        else:
            print(json.dumps(report, indent=2))
    return exit_code


if __name__ == "__main__":
    raise SystemExit(main())
