# THIS FILE WAS GENERATED BY scripts/generate_tests_from_yaml.py
# Source: docs/architecture/careervp_prompts/cv-tailoring/tests/test_P1_output_schema.yaml
# Spec ID: TEST-CVT-P1
# Re-run the script to regenerate, or edit manually then remove this header.
#
# IMPORTANT: These tests fail until the corresponding spec is implemented.
# See the YAML spec for acceptance criteria and traceability matrix.
"""
Unit tests: TailoredCVResponse schema must use cv_sections (not tailored_cv text blob).
Spec: CVT-P1 — Structured cv_sections Output Schema
These tests fail if CVT-P1 has not been implemented.
"""

from __future__ import annotations

import pytest
from pydantic import ValidationError

from careervp.models.cv_tailoring_models import (
    CVContact,
    CVExperienceItem,
    CVSections,
    CVSkills,
    TailoredCVResponse,
)


@pytest.fixture
def sample_cv_sections() -> CVSections:
    return CVSections(
        contact=CVContact(
            name='Alex Candidate',
            email='alex@example.com',
            phone='+1-555-0100',
            linkedin=None,
            location='New York, NY',
        ),
        summary=(
            'Platform engineer with 8 years driving cloud reliability across distributed SaaS products. Led Kubernetes migration at Nimbus Labs.'
        ),
        skills=CVSkills(
            technical=['Python', 'AWS', 'Kubernetes', 'Terraform'],
            soft=['Leadership'],
        ),
        experience=[
            CVExperienceItem(
                company='Nimbus Labs',
                title='Senior Software Engineer',
                start_date='01/2021',
                end_date='Present',
                bullets=[
                    'Drove | Kubernetes migration for 12 services | Increased reliability by 35%',
                ],
            )
        ],
        education=[],
        certifications=[],
    )


@pytest.fixture
def sample_response(sample_cv_sections: CVSections) -> TailoredCVResponse:
    return TailoredCVResponse(
        cv_sections=sample_cv_sections,
        ats_score=82,
        ats_issues=[],
        keyword_match_score=9,
        keywords_missing=[],
        fact_verification_passed=True,
        language='en',
    )


@pytest.mark.unit
def test_cv_sections_model_is_importable() -> None:
    from careervp.models.cv_tailoring_models import CVContact, CVExperienceItem, CVSections, CVSkills  # noqa: F401


@pytest.mark.unit
def test_tailored_cv_response_has_cv_sections_not_text_blob(
    sample_response: TailoredCVResponse,
) -> None:
    assert hasattr(sample_response, 'cv_sections'), 'TailoredCVResponse must have cv_sections — CVT-P1 not implemented'
    assert not hasattr(sample_response, 'tailored_cv'), 'tailored_cv text blob must be removed — CVT-P1 not implemented'
    assert not isinstance(sample_response.cv_sections, str)


@pytest.mark.unit
def test_ats_score_is_int_in_0_to_100_range(sample_response: TailoredCVResponse) -> None:
    assert isinstance(sample_response.ats_score, int), f'ats_score must be int, got {type(sample_response.ats_score).__name__} — CVT-P1'
    assert 0 <= sample_response.ats_score <= 100


@pytest.mark.unit
def test_fact_verification_passed_is_bool(sample_response: TailoredCVResponse) -> None:
    assert hasattr(sample_response, 'fact_verification_passed'), 'Missing field — CVT-P1'
    assert isinstance(sample_response.fact_verification_passed, bool)


@pytest.mark.unit
def test_experience_item_has_bullets_array(sample_cv_sections: CVSections) -> None:
    exp = sample_cv_sections.experience[0]
    assert isinstance(exp.bullets, list)
    assert len(exp.bullets) >= 1
    assert all(isinstance(b, str) for b in exp.bullets)


@pytest.mark.unit
def test_keywords_missing_is_list_and_keyword_match_score_is_1_to_10(
    sample_response: TailoredCVResponse,
) -> None:
    assert isinstance(sample_response.keywords_missing, list)
    assert isinstance(sample_response.keyword_match_score, int)
    assert 1 <= sample_response.keyword_match_score <= 10


@pytest.mark.unit
def test_tailored_cv_response_rejects_float_ats_score(sample_cv_sections: CVSections) -> None:
    with pytest.raises((ValidationError, TypeError)):
        TailoredCVResponse(
            cv_sections=sample_cv_sections,
            ats_score=8.5,  # type: ignore[arg-type]
            ats_issues=[],
            keyword_match_score=9,
            keywords_missing=[],
            fact_verification_passed=True,
            language='en',
        )
