# THIS FILE WAS GENERATED BY scripts/generate_tests_from_yaml.py
# Source: docs/architecture/careervp_prompts/cv-tailoring/tests/test_P5_cv_tailoring_regen_artifact_id.yaml
# Spec ID: TEST-CVT-P5
# Re-run the script to regenerate, or edit manually then remove this header.
#
# IMPORTANT: These tests fail until the corresponding spec is implemented.
# See the YAML spec for acceptance criteria and traceability matrix.
"""
Unit tests: CV Tailoring regenerate must persist artifact_id in application record.
Spec: CVT-P5 — CV Tailoring Regenerate shows stale Edit link (artifact_id not persisted)

These tests fail if CVT-P5 has not been implemented:
  - T-P5-01..05: ImportError or AttributeError (backend function absent / not wired)
  - T-P5-06: AssertionError (frontend optimistic hub update absent)
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest


# ─── T-P5-01: function must be importable ─────────────────────────────────────


@pytest.mark.unit
def test_cv_tailoring_handler_has_update_application_artifact() -> None:
    from careervp.handlers.cv_tailoring_handler import _update_application_artifact  # noqa: F401

    assert callable(_update_application_artifact), '_update_application_artifact must be a callable in cv_tailoring_handler — CVT-P5 not implemented'


# ─── T-P5-02: non-fatal without env var ───────────────────────────────────────


@pytest.mark.unit
def test_update_application_artifact_is_non_fatal_without_table_env(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    from careervp.handlers.cv_tailoring_handler import _update_application_artifact

    monkeypatch.delenv('APPLICATIONS_TABLE_NAME', raising=False)
    monkeypatch.delenv('DYNAMODB_TABLE_NAME', raising=False)
    monkeypatch.delenv('TABLE_NAME', raising=False)

    _update_application_artifact(
        application_id='app-123',
        user_id='user-456',
        artifact_type='cv_tailored',
        artifact_id='cv-tail-789',
    )


# ─── T-P5-03: calls ApplicationRepository.update_artifact_with_id ─────────────


@pytest.mark.unit
def test_update_application_artifact_calls_repository(monkeypatch: pytest.MonkeyPatch) -> None:
    import careervp.handlers.cv_tailoring_handler as handler_module
    from careervp.handlers.cv_tailoring_handler import _update_application_artifact

    monkeypatch.setenv('APPLICATIONS_TABLE_NAME', 'test-applications-table')

    mock_repo = MagicMock()
    # _update_application_artifact does a local import inside the function body,
    # so we must patch at the source module, not on handler_module.
    with patch('careervp.dal.application_repository.ApplicationRepository', return_value=mock_repo):
        with patch.object(handler_module, 'DynamoDalHandler'):
            _update_application_artifact(
                application_id='app-abc',
                user_id='user-xyz',
                artifact_type='cv_tailored',
                artifact_id='cv-tail-new',
            )

    mock_repo.update_artifact_with_id.assert_called_once_with(
        application_id='app-abc',
        user_id='user-xyz',
        artifact_type='cv_tailored',
        status='completed',
        artifact_id='cv-tail-new',
    )


# ─── T-P5-04: handler wires _update_application_artifact ─────────────────────


@pytest.mark.unit
def test_handle_openapi_async_generate_calls_update_application_artifact(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    import careervp.handlers.cv_tailoring_handler as handler_module

    assert hasattr(handler_module, '_update_application_artifact'), (
        '_update_application_artifact not found in cv_tailoring_handler — CVT-P5 not implemented'
    )

    monkeypatch.setenv('DYNAMODB_TABLE_NAME', 'test-cv-table')

    from careervp.models.cv_tailoring_models import (
        CVContactSection,
        CVExperienceSection,
        CVSections,
        CVSkillsSection,
        Stage3Result,
    )
    from careervp.models.result import Result, ResultCode

    cv_sections = CVSections(
        contact=CVContactSection(name='Test User', email='test@example.com'),
        summary='Senior engineer with 10 years of experience building scalable cloud systems.',
        skills=CVSkillsSection(technical=['Python'], soft=[]),
        experience=[
            CVExperienceSection(
                company='Acme', title='Engineer', start_date='01/2020', bullets=['Built distributed system handling 1M+ events per day.']
            )
        ],
        education=[],
        certifications=[],
    )
    mock_pipeline_result = Result(
        success=True,
        data=Stage3Result(cv_sections=cv_sections, fact_verification_passed=True, ats_keyword_score=70),
        code=ResultCode.SUCCESS,
    )

    mock_dal = MagicMock()
    mock_dal.get_cv.return_value = MagicMock(professional_summary='Backend engineer', cv_id='cv-123')
    mock_dal._get_db_handler.return_value = MagicMock()

    with patch.object(handler_module, 'DynamoDalHandler', return_value=mock_dal):
        with patch.object(handler_module, 'JobsRepository') as mock_jobs_cls:
            mock_jobs_cls.return_value.get_job.return_value = {'description': 'Test job', 'title': 'Engineer'}
            with patch.object(handler_module, 'LLMClient'):
                with patch.object(handler_module, 'run_cv_tailoring_pipeline', return_value=mock_pipeline_result):
                    with patch.object(handler_module, '_update_application_artifact') as mock_update:
                        handler_module._handle_openapi_async_generate(
                            event={},
                            request_data={'cv_id': 'cv-123', 'job_id': 'job-456', 'vpr_id': None},
                            headers={},
                            user_id='user-789',
                        )

    mock_update.assert_called_once()
    kwargs = mock_update.call_args.kwargs
    assert kwargs.get('application_id') == 'job-456', f"application_id must equal job_id='job-456', got {kwargs.get('application_id')}"
    assert kwargs.get('user_id') == 'user-789', f"user_id must be 'user-789', got {kwargs.get('user_id')}"
    assert kwargs.get('artifact_type') == 'cv_tailored', f"artifact_type must be 'cv_tailored', got {kwargs.get('artifact_type')}"
    artifact_id = kwargs.get('artifact_id', '')
    assert isinstance(artifact_id, str) and artifact_id.startswith('cv-tail-'), f"artifact_id must start with 'cv-tail-', got {artifact_id!r}"


# ─── T-P5-05: response request_id matches artifact_id ────────────────────────


@pytest.mark.unit
def test_handle_openapi_async_generate_response_contains_request_id(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    import careervp.handlers.cv_tailoring_handler as handler_module

    assert hasattr(handler_module, '_update_application_artifact'), (
        '_update_application_artifact not in cv_tailoring_handler — CVT-P5 not implemented'
    )

    monkeypatch.setenv('DYNAMODB_TABLE_NAME', 'test-cv-table')

    captured_artifact_id: list[str] = []

    def capture_update(**kwargs: object) -> None:
        captured_artifact_id.append(str(kwargs.get('artifact_id', '')))

    from careervp.models.cv_tailoring_models import (
        CVContactSection,
        CVExperienceSection,
        CVSections,
        CVSkillsSection,
        Stage3Result,
    )
    from careervp.models.result import Result, ResultCode

    cv_sections = CVSections(
        contact=CVContactSection(name='Test User', email='test@example.com'),
        summary='Senior engineer with 10 years of experience building scalable cloud systems.',
        skills=CVSkillsSection(technical=['Python'], soft=[]),
        experience=[
            CVExperienceSection(
                company='Acme', title='Engineer', start_date='01/2020', bullets=['Built distributed system handling 1M+ events per day.']
            )
        ],
        education=[],
        certifications=[],
    )
    mock_pipeline_result = Result(
        success=True,
        data=Stage3Result(cv_sections=cv_sections, fact_verification_passed=True, ats_keyword_score=70),
        code=ResultCode.SUCCESS,
    )

    mock_dal = MagicMock()
    mock_dal.get_cv.return_value = MagicMock(professional_summary='Backend engineer', cv_id='cv-111')
    mock_dal._get_db_handler.return_value = MagicMock()

    with patch.object(handler_module, 'DynamoDalHandler', return_value=mock_dal):
        with patch.object(handler_module, 'JobsRepository') as mock_jobs_cls:
            mock_jobs_cls.return_value.get_job.return_value = {'description': 'Test job', 'title': 'Engineer'}
            with patch.object(handler_module, 'LLMClient'):
                with patch.object(handler_module, 'run_cv_tailoring_pipeline', return_value=mock_pipeline_result):
                    with patch.object(handler_module, '_update_application_artifact', side_effect=capture_update):
                        result = handler_module._handle_openapi_async_generate(
                            event={},
                            request_data={'cv_id': 'cv-111', 'job_id': 'job-222', 'vpr_id': None},
                            headers={},
                            user_id='user-333',
                        )

    body = json.loads(result['body'])
    response_request_id = body.get('request_id', '')
    assert len(captured_artifact_id) == 1, 'Expected exactly one _update_application_artifact call'
    assert captured_artifact_id[0] == response_request_id, (
        f'artifact_id passed to _update_application_artifact ({captured_artifact_id[0]!r}) must match response request_id ({response_request_id!r})'
    )


# ─── T-P5-06: frontend optimistic hub update ─────────────────────────────────


@pytest.mark.unit
def test_handle_generate_cv_updates_hub_on_completed_status() -> None:
    page_path = Path(__file__).parents[5] / 'frontend' / 'app' / 'dashboard' / 'jobs' / '[jobId]' / 'page.tsx'
    assert page_path.exists(), f'page.tsx not found at {page_path}'

    content = page_path.read_text(encoding='utf-8')

    func_match = re.search(
        r'const handleGenerateCV\s*=\s*async.*?^\s{2}\};',
        content,
        re.DOTALL | re.MULTILINE,
    )
    assert func_match, 'handleGenerateCV function not found in page.tsx'
    func_body = func_match.group(0)

    completed_idx = func_body.find('"completed"')
    assert completed_idx != -1, 'completed branch not found in handleGenerateCV'

    completed_section = func_body[completed_idx:]
    else_idx = completed_section.find('} else {')
    if else_idx != -1:
        completed_section = completed_section[:else_idx]

    missing: list[str] = []
    if 'setHub' not in completed_section:
        missing.append('setHub()')
    if 'cv_tailored' not in completed_section:
        missing.append('cv_tailored key')
    if 'artifact_id' not in completed_section:
        missing.append('artifact_id key')
    if 'task.request_id' not in completed_section:
        missing.append('task.request_id value')

    assert not missing, (
        'handleGenerateCV completed branch is missing optimistic hub update. '
        f'Not found: {", ".join(missing)}. '
        'Add setHub updating cv_tailored.artifact_id = task.request_id '
        'before refreshHub() — CVT-P5 not implemented'
    )
