# THIS FILE WAS GENERATED BY scripts/generate_tests_from_yaml.py
# Source: docs/architecture/careervp_prompts/cv-tailoring/tests/test_P2_three_stage_pipeline.yaml
# Spec ID: TEST-CVT-P2
# Re-run the script to regenerate, or edit manually then remove this header.
#
# IMPORTANT: These tests fail until the corresponding spec is implemented.
# See the YAML spec for acceptance criteria and traceability matrix.
"""
Unit tests for the three-stage CV tailoring pipeline.
Spec: CVT-P2 — Three-Stage LLM Pipeline
Tests fail with ImportError until cv_tailoring_pipeline.py is created.
LLM calls are mocked — tests verify shapes, routing, and fact verification correctness.
"""

from __future__ import annotations

from unittest.mock import MagicMock

import pytest

from careervp.models.cv_tailoring_models import (
    GapAnalysisResponses,
    ParsedFacts,
)

# --- Fixtures are defined in conftest.py for this test module ---
# See test_P2_three_stage_pipeline.yaml fixtures section for fixture implementations.

# fmt: off


@pytest.mark.unit
def test_stage1_output_model_is_importable() -> None:
    from careervp.logic.cv_tailoring_pipeline import Stage1Output  # noqa: F401


@pytest.mark.unit
def test_stage1_returns_12_to_18_primary_keywords(
    sample_parsed_facts: ParsedFacts,
    mock_llm_stage1: MagicMock,
) -> None:
    from careervp.logic.cv_tailoring_pipeline import Stage1Output, run_stage1_keyword_mapping

    result = run_stage1_keyword_mapping(
        vpr=None,
        job_description="Lead cloud platform reliability and microservices adoption.",
        parsed_facts=sample_parsed_facts,
        gap_responses=GapAnalysisResponses(responses=[]),
        llm_client=mock_llm_stage1,
    )
    assert isinstance(result, Stage1Output)
    assert 12 <= len(result.primary_keywords) <= 18, (
        f"Stage1 returned {len(result.primary_keywords)} keywords, expected 12-18"
    )


@pytest.mark.unit
def test_stage3_rejects_hallucinated_company(sample_parsed_facts: ParsedFacts) -> None:
    from careervp.logic.cv_tailoring_pipeline import Stage2Output, run_stage3_fact_verification
    from careervp.models.cv_tailoring_models import (
        CVContact,
        CVExperienceItem,
        CVSections,
        CVSkills,
        Stage2Verification,
    )

    fake_sections = CVSections(
        contact=CVContact(name="Alex Candidate", email="alex@example.com",
                          phone=None, linkedin=None, location=None),
        summary="Platform engineer with extensive cloud infrastructure and Kubernetes experience.",
        skills=CVSkills(technical=["Python"], soft=[]),
        experience=[
            CVExperienceItem(
                company="FAKE CORP INC",
                title="Senior Engineer",
                start_date="01/2021",
                end_date="Present",
                bullets=["Built and maintained cloud infrastructure platform."],
            )
        ],
        education=[],
        certifications=[],
    )
    stage2 = Stage2Output(
        verification=Stage2Verification(
            ats_keyword_score=8,
            keywords_added_in_review=[],
            summary_rewritten=False,
            fact_verification_passed=True,
            hallucination_flags=[],
        ),
        cv_sections=fake_sections,
    )

    result = run_stage3_fact_verification(stage2_output=stage2, parsed_facts=sample_parsed_facts)
    assert result.fact_verification_passed is False, (
        "Stage3 must catch hallucinated company — CVT-P2"
    )


@pytest.mark.unit
def test_stage1_system_prompt_matches_spec() -> None:
    from careervp.logic.cv_tailoring_prompt import build_stage1_system_prompt

    prompt = build_stage1_system_prompt()
    assert "CRITICAL RULE" in prompt
    assert "ONLY valid JSON" in prompt


@pytest.mark.unit
def test_stage2_system_prompt_has_7_rules() -> None:
    from careervp.logic.cv_tailoring_prompt import build_stage2_system_prompt

    prompt = build_stage2_system_prompt()
    for phrase in ["ZERO HALLUCINATIONS", "CAR/STAR", "450-600 words", "Anti-AI detection"]:
        assert phrase in prompt, f"Missing rule: {phrase}"
