# THIS FILE WAS GENERATED BY scripts/generate_tests_from_yaml.py
# Source: docs/architecture/careervp_prompts/cv-tailoring/tests/test_P3_ground_truth_inputs.yaml
# Spec ID: TEST-CVT-P3
# Re-run the script to regenerate, or edit manually then remove this header.
#
# IMPORTANT: These tests fail until the corresponding spec is implemented.
# See the YAML spec for acceptance criteria and traceability matrix.
"""
Unit tests: parsed_facts, GapAnalysisResponses, CompanyContext wiring in CVTailoringLogic.
Spec: CVT-P3 — Ground Truth Inputs
Tests fail with ImportError until CVT-P3 is implemented.
tailor_cv() is async — uses @pytest.mark.asyncio.
run_stage3_fact_verification() is sync — those tests remain sync.
"""

from __future__ import annotations

from unittest.mock import MagicMock, patch

import pytest
from pydantic import ValidationError

from careervp.models.cv_tailoring_models import (
    GapAnalysisResponses,
    ParsedFacts,
)

# Fixtures are defined in conftest.py for this test module.
# See test_P3_ground_truth_inputs.yaml fixtures section.


@pytest.mark.unit
def test_parsed_facts_model_is_importable() -> None:
    from careervp.models.cv_tailoring_models import ParsedFacts  # noqa: F401


@pytest.mark.unit
def test_parsed_facts_rejects_missing_required_fields() -> None:
    with pytest.raises((ValidationError, TypeError)):
        ParsedFacts(  # type: ignore[call-arg]
            email='alex@example.com',
            work_experience=[],
            education=[],
            skills={'technical': [], 'soft': []},
            certifications=[],
            languages=[],
            summary_original='',
        )


@pytest.mark.unit
def test_gap_analysis_responses_accepts_empty_list() -> None:
    gar = GapAnalysisResponses(responses=[])
    assert gar.responses == []


@pytest.mark.unit
@pytest.mark.asyncio
async def test_parsed_facts_passed_to_stage1() -> None:
    """Test that parsed_facts is passed to the pipeline."""
    from careervp.logic.cv_tailoring_logic import CVTailoringLogic
    from careervp.models.cv_tailoring_models import (
        CVContactSection,
        CVExperienceSection,
        CVSections,
        CVSkillsSection,
    )

    # Create mock DAL that returns a user CV
    mock_dal = MagicMock()
    mock_dal.get_cv = MagicMock(
        return_value=MagicMock(
            user_id='user-001',
            cv_id='cv-001',
            full_name='Alex Candidate',
            email='alex@example.com',
            phone='+1-555-0100',
            location='New York, NY',
            work_experience=[],
            education=[],
            skills=[],
            certifications=[],
            languages=[],
            professional_summary='Test summary',
        )
    )
    mock_dal.get_tailored_cv = MagicMock(return_value=MagicMock(success=True, data=None))
    mock_dal.get_vpr = MagicMock(return_value=MagicMock(success=True, data=None))

    # Create proper CVSections for mock
    mock_cv_sections = CVSections(
        contact=CVContactSection(name='Alex Candidate', email='alex@example.com'),
        summary='Experienced software engineer with expertise in cloud platforms and distributed systems. Led multiple teams to deliver high-impact projects.',
        skills=CVSkillsSection(technical=['Python', 'AWS', 'Kubernetes'], soft=[]),
        experience=[
            CVExperienceSection(
                company='Tech Corp',
                title='Senior Engineer',
                start_date='01/2020',
                end_date='Present',
                bullets=['Led team of 5 engineers'],
            )
        ],
        education=[],
        certifications=[],
    )

    with patch('careervp.logic.cv_tailoring_logic.run_cv_tailoring_pipeline') as mock_pipeline:
        mock_pipeline.return_value = MagicMock(
            success=True,
            data=MagicMock(
                cv_sections=mock_cv_sections,
                fact_verification_passed=True,
                items_corrected=[],
                items_removed=[],
            ),
        )
        logic = CVTailoringLogic(dal=mock_dal, llm_client=MagicMock())
        await logic.tailor_cv(
            request=MagicMock(
                cv_id='cv-001',
                job_description='Lead cloud platform.',
                vpr_id=None,
                idempotency_key=None,
                preferences=None,
            ),
            user_id='user-001',
        )

    call_kwargs = mock_pipeline.call_args.kwargs
    assert 'parsed_facts' in call_kwargs, 'parsed_facts not passed to pipeline — CVT-P3'
    assert isinstance(call_kwargs.get('parsed_facts'), ParsedFacts), 'parsed_facts must be ParsedFacts instance'


@pytest.mark.unit
@pytest.mark.asyncio
async def test_parsed_facts_constructed_from_user_cv_when_absent() -> None:
    """Covers test-data state: cv_record.parsed_facts is None."""
    from careervp.logic.cv_tailoring_logic import CVTailoringLogic
    from careervp.models.cv_tailoring_models import (
        CVContactSection,
        CVExperienceSection,
        CVSections,
        CVSkillsSection,
    )

    mock_dal = MagicMock()
    mock_dal.get_cv = MagicMock(
        return_value=MagicMock(
            user_id='user-001',
            cv_id='cv-001',
            full_name='Alex Candidate',
            email='alex@example.com',
            phone='+1-555-0100',
            location='New York, NY',
            work_experience=[],
            education=[],
            skills=[],
            certifications=[],
            languages=[],
            professional_summary='Test summary',
        )
    )
    mock_dal.get_tailored_cv = MagicMock(return_value=MagicMock(success=True, data=None))
    mock_dal.get_vpr = MagicMock(return_value=MagicMock(success=True, data=None))

    mock_cv_sections = CVSections(
        contact=CVContactSection(name='Alex Candidate', email='alex@example.com'),
        summary='Experienced software engineer with expertise in cloud platforms and distributed systems.',
        skills=CVSkillsSection(technical=['Python', 'AWS'], soft=[]),
        experience=[
            CVExperienceSection(
                company='Tech Corp',
                title='Engineer',
                start_date='01/2018',
                end_date='12/2020',
                bullets=['Built APIs'],
            )
        ],
        education=[],
        certifications=[],
    )

    with patch('careervp.logic.cv_tailoring_logic.run_cv_tailoring_pipeline') as mock_pipeline:
        mock_pipeline.return_value = MagicMock(
            success=True,
            data=MagicMock(
                cv_sections=mock_cv_sections,
                fact_verification_passed=True,
                items_corrected=[],
                items_removed=[],
            ),
        )
        logic = CVTailoringLogic(dal=mock_dal, llm_client=MagicMock())
        await logic.tailor_cv(
            request=MagicMock(
                cv_id='cv-001',
                job_description='Lead cloud platform.',
                vpr_id=None,
                idempotency_key=None,
                preferences=None,
            ),
            user_id='user-001',
        )

    call_kwargs = mock_pipeline.call_args.kwargs
    pf = call_kwargs.get('parsed_facts')
    assert isinstance(pf, ParsedFacts), 'Must construct ParsedFacts from UserCV — CVT-P3'
    assert pf.name == 'Alex Candidate'
