# THIS FILE WAS GENERATED BY scripts/generate_tests_from_yaml.py
# Source: docs/architecture/careervp_prompts/cv-tailoring/tests/test_P4_ats_scoring_100pt.yaml
# Spec ID: TEST-CVT-P4
# Re-run the script to regenerate, or edit manually then remove this header.
#
# IMPORTANT: These tests fail until the corresponding spec is implemented.
# See the YAML spec for acceptance criteria and traceability matrix.
"""
Unit tests: ATS scoring algorithm on 0-100 integer scale per spec §6.
Spec: CVT-P4 — ATS Scoring 0-100
Tests T-P4-01 and T-P4-02 fail immediately until TARGET_ATS_SCORE/ANTI_AI_MIN_SCORE are updated.
Tests T-P4-03 through T-P4-09 fail until calculate_ats_score() returns int 0-100.
Tests T-P4-10 and T-P4-11 fail until existing tests are updated to new scale.
"""

from __future__ import annotations

import pathlib

import pytest

from careervp.logic.cv_tailoring import KeywordMap
from careervp.models.cv import ContactInfo, Education, Skill, WorkExperience
from careervp.models.cv_tailoring_models import TailoredCV

SAMPLE_KEYWORDS = [
    'Kubernetes',
    'Python',
    'AWS',
    'CI/CD',
    'reliability',
    'microservices',
    'platform',
    'observability',
    'Terraform',
    'SRE',
    'distributed',
    'incident',
]


@pytest.fixture
def sample_keyword_map() -> KeywordMap:
    return KeywordMap(
        required=['Kubernetes', 'Python', 'AWS'],
        preferred=['CI/CD', 'reliability', 'microservices'],
        nice_to_have=['platform', 'observability', 'Terraform', 'SRE', 'distributed', 'incident'],
        mapped_keywords={k: ['experience'] for k in SAMPLE_KEYWORDS},
        keyword_categories={k: 'required' if k in ['Kubernetes', 'Python', 'AWS'] else 'preferred' for k in SAMPLE_KEYWORDS},
    )


@pytest.fixture
def perfect_cv_sections() -> TailoredCV:
    return TailoredCV(
        user_id='user-1',
        cv_id='cv-1',
        full_name='Alex Candidate',
        email='alex@example.com',
        contact_info=ContactInfo(name='Alex Candidate', email='alex@example.com'),
        professional_summary=(
            'Senior Kubernetes platform engineer with AWS and Python expertise, '
            'driving CI/CD reliability across distributed microservices. '
            'Built observability frameworks using Terraform and SRE practices, '
            'reducing incident response time by 40% and improving platform uptime by 99.9%.'
        ),
        work_experience=[
            WorkExperience(
                company='Nimbus Labs',
                role='Senior Software Engineer',
                start_date='01/2021',
                end_date='Present',
                achievements=[
                    'Built | Kubernetes CI/CD pipeline for 12 microservices | Increased reliability by 35%',
                    'Automated | AWS observability with Terraform | Reduced incident response by 40%',
                    'Led | Distributed SRE platform migration | Improved uptime from 99.5% to 99.9%',
                ],
                technologies=['Python', 'AWS', 'Kubernetes', 'Terraform', 'CI/CD'],
            )
        ],
        education=[Education(institution='MIT', degree='BSc', field_of_study='CS', graduation_date='06/2016', honors=[])],
        skills=[Skill(name='Python'), Skill(name='AWS'), Skill(name='Kubernetes'), Skill(name='Terraform'), Skill(name='CI/CD')],
        certifications=[],
        languages=['en'],
    )


@pytest.fixture
def empty_cv_sections() -> TailoredCV:
    return TailoredCV(
        user_id='user-1',
        cv_id='cv-1',
        full_name='A',
        email='a@b.com',
        contact_info=ContactInfo(name='A', email='a@b.com'),
        professional_summary='',
        work_experience=[],
        education=[],
        skills=[],
        certifications=[],
        languages=['en'],
    )


@pytest.mark.unit
def test_target_ats_score_constant_is_80() -> None:
    from careervp.logic.cv_tailoring import TARGET_ATS_SCORE

    assert TARGET_ATS_SCORE == 80, f'TARGET_ATS_SCORE={TARGET_ATS_SCORE}, expected 80 — CVT-P4'


@pytest.mark.unit
def test_anti_ai_min_score_constant_is_90() -> None:
    from careervp.logic.cv_tailoring import ANTI_AI_MIN_SCORE

    assert ANTI_AI_MIN_SCORE == 90, f'ANTI_AI_MIN_SCORE={ANTI_AI_MIN_SCORE}, expected 90 — CVT-P4'


@pytest.mark.unit
def test_ats_score_returns_int_not_float(perfect_cv_sections: TailoredCV, sample_keyword_map: KeywordMap) -> None:
    from careervp.logic.cv_tailoring import calculate_ats_score

    score = calculate_ats_score(perfect_cv_sections, sample_keyword_map)
    assert isinstance(score, int), f'calculate_ats_score must return int, got {type(score).__name__} — CVT-P4'


@pytest.mark.unit
def test_ats_score_range_is_0_to_100(perfect_cv_sections: TailoredCV, sample_keyword_map: KeywordMap) -> None:
    from careervp.logic.cv_tailoring import calculate_ats_score

    score = calculate_ats_score(perfect_cv_sections, sample_keyword_map)
    assert 0 <= score <= 100, f'Score {score} outside 0-100 — CVT-P4'


@pytest.mark.unit
def test_empty_cv_scores_0(empty_cv_sections: TailoredCV) -> None:
    from careervp.logic.cv_tailoring import calculate_ats_score

    empty_map = KeywordMap(required=[], preferred=[], nice_to_have=[], mapped_keywords={}, keyword_categories={})
    assert calculate_ats_score(empty_cv_sections, empty_map) == 0


@pytest.mark.unit
def test_existing_test_cv_tailoring_uses_new_scale() -> None:
    test_file = pathlib.Path(__file__).parents[1] / 'test_cv_tailoring.py'
    assert test_file.exists()
    content = test_file.read_text(encoding='utf-8')
    assert '0.0 <= score <= 10.0' not in content, 'Old 0-10 scale assertion not updated — CVT-P4'
    assert '0 <= score <= 100' in content, 'Missing 0-100 scale assertion — CVT-P4'


@pytest.mark.unit
def test_existing_final_ats_score_threshold_uses_new_scale() -> None:
    test_file = pathlib.Path(__file__).parents[1] / 'test_cv_tailoring.py'
    assert test_file.exists()
    content = test_file.read_text(encoding='utf-8')
    assert 'ats_score >= 8.0' not in content, 'Old >= 8.0 threshold not updated — CVT-P4'
    assert 'ats_score >= 80' in content, 'Missing >= 80 threshold — CVT-P4'
