"""
Generate Python pytest stub files from YAML test spec files.

Usage:
    # Generate all test stubs from the cv-tailoring test specs:
    python scripts/generate_tests_from_yaml.py \
        docs/architecture/careervp_prompts/cv-tailoring/tests/

    # Generate a single spec:
    python scripts/generate_tests_from_yaml.py \
        docs/architecture/careervp_prompts/cv-tailoring/tests/test_P1_output_schema.yaml

    # Preview without writing (dry run):
    python scripts/generate_tests_from_yaml.py \
        docs/architecture/careervp_prompts/cv-tailoring/tests/ --dry-run

    # Overwrite existing files:
    python scripts/generate_tests_from_yaml.py \
        docs/architecture/careervp_prompts/cv-tailoring/tests/ --force

    # Specify a custom repo root (default: directory containing scripts/):
    python scripts/generate_tests_from_yaml.py \
        docs/architecture/careervp_prompts/cv-tailoring/tests/ \
        --root /path/to/repo

How it works:
    Each YAML test spec file must contain a `full_file_template` key whose value
    is the complete Python source of the test file to generate.

    The `test_file` key (or `test_files.primary`) determines the output path,
    relative to the repo root.

    Files are NOT overwritten unless --force is passed. Existing files are
    reported with a warning so the implementer can review diffs manually.

YAML spec format expected:
    test_spec_id: TEST-CVT-P1
    test_file: src/backend/tests/unit/cv_tailoring/test_output_schema.py
    # OR:
    test_files:
      primary: src/backend/tests/unit/cv_tailoring/test_output_schema.py
    full_file_template: |
      <complete Python test file content>
"""

from __future__ import annotations

import argparse
import sys
import textwrap
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML not installed. Run: uv add pyyaml --dev", file=sys.stderr)
    sys.exit(1)


# ─── Constants ────────────────────────────────────────────────────────────────

SPEC_KEY_TEST_FILE = "test_file"
SPEC_KEY_TEST_FILES = "test_files"
SPEC_KEY_TEMPLATE = "full_file_template"
SPEC_KEY_ID = "test_spec_id"

BANNER_WIDTH = 79
GENERATED_HEADER = textwrap.dedent(
    """\
    # THIS FILE WAS GENERATED BY scripts/generate_tests_from_yaml.py
    # Source: {source_yaml}
    # Spec ID: {spec_id}
    # Re-run the script to regenerate, or edit manually then remove this header.
    #
    # IMPORTANT: These tests fail until the corresponding spec is implemented.
    # See the YAML spec for acceptance criteria and traceability matrix.
    """
)


# ─── Helpers ──────────────────────────────────────────────────────────────────


def _find_repo_root(start: Path) -> Path:
    """Walk upward from start to find the repo root (contains pyproject.toml or .git)."""
    current = start.resolve()
    for parent in [current, *current.parents]:
        if (parent / ".git").exists() or (parent / "pyproject.toml").exists():
            return parent
    return current  # fallback


def _load_yaml(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as fh:
        data = yaml.safe_load(fh)
    if not isinstance(data, dict):
        raise ValueError(
            f"{path}: YAML root must be a mapping, got {type(data).__name__}"
        )
    return data


def _get_test_file_path(spec: dict[str, Any], spec_path: Path) -> str | None:
    """Extract the primary test_file path from the spec."""
    if SPEC_KEY_TEST_FILE in spec:
        return spec[SPEC_KEY_TEST_FILE]
    if SPEC_KEY_TEST_FILES in spec:
        test_files = spec[SPEC_KEY_TEST_FILES]
        if isinstance(test_files, str):
            return test_files
        if isinstance(test_files, dict):
            return test_files.get("primary")
        if isinstance(test_files, list) and test_files:
            # Take the first entry
            first = test_files[0]
            return first if isinstance(first, str) else None
    return None


def _get_template(spec: dict[str, Any]) -> str | None:
    return spec.get(SPEC_KEY_TEMPLATE)


def _build_output_content(template: str, spec_id: str, source_yaml: str) -> str:
    header = GENERATED_HEADER.format(spec_id=spec_id, source_yaml=source_yaml)
    return header + template


def _print_banner(char: str = "─") -> None:
    print(char * BANNER_WIDTH)


# ─── Core processing ──────────────────────────────────────────────────────────


def process_spec_file(
    spec_path: Path,
    repo_root: Path,
    *,
    dry_run: bool,
    force: bool,
) -> tuple[str, str]:
    """
    Process a single YAML spec file.

    Returns:
        (status, message) where status is one of:
        "written", "skipped", "dry_run", "no_template", "no_test_file", "error"
    """
    try:
        spec = _load_yaml(spec_path)
    except Exception as exc:
        return "error", f"Failed to parse YAML: {exc}"

    spec_id = spec.get(SPEC_KEY_ID, spec_path.stem)
    template = _get_template(spec)
    test_file_rel = _get_test_file_path(spec, spec_path)

    if template is None:
        return "no_template", f"No '{SPEC_KEY_TEMPLATE}' key — skipping"

    if test_file_rel is None:
        return (
            "no_test_file",
            f"No '{SPEC_KEY_TEST_FILE}' key — cannot determine output path",
        )

    output_path = repo_root / test_file_rel

    content = _build_output_content(
        template=template,
        spec_id=spec_id,
        source_yaml=str(spec_path.relative_to(repo_root)),
    )

    if dry_run:
        return "dry_run", f"Would write → {test_file_rel} ({len(content)} bytes)"

    if output_path.exists() and not force:
        return (
            "skipped",
            f"Already exists → {test_file_rel}  (use --force to overwrite)",
        )

    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Ensure __init__.py files exist up the path for pytest discovery
    _ensure_init_files(output_path.parent, repo_root)

    output_path.write_text(content, encoding="utf-8")
    return "written", f"Written → {test_file_rel}"


def _ensure_init_files(directory: Path, repo_root: Path) -> None:
    """Create empty __init__.py in directory and ancestors up to tests/."""
    current = directory
    while current != repo_root and current.name not in {"src", "backend", ""}:
        init = current / "__init__.py"
        if not init.exists() and current.is_dir():
            # Only create __init__.py inside test directories
            if "test" in current.name or "test" in str(current.relative_to(repo_root)):
                init.touch()
        if current.parent == current:
            break
        current = current.parent


# ─── Entry point ──────────────────────────────────────────────────────────────


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate Python pytest stub files from YAML test spec files.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "paths",
        nargs="+",
        help="YAML test spec file(s) or directory containing them.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would be written without actually writing.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing test files.",
    )
    parser.add_argument(
        "--root",
        default=None,
        help="Repo root directory. Defaults to auto-detected root.",
    )
    args = parser.parse_args(argv)

    repo_root = (
        Path(args.root).resolve() if args.root else _find_repo_root(Path(__file__))
    )

    # Collect all YAML files to process
    yaml_files: list[Path] = []
    for path_str in args.paths:
        p = Path(path_str)
        if not p.is_absolute():
            p = Path.cwd() / p
        p = p.resolve()
        if p.is_dir():
            yaml_files.extend(sorted(p.glob("test_*.yaml")))
        elif p.suffix in {".yaml", ".yml"} and p.exists():
            yaml_files.append(p)
        else:
            print(
                f"WARNING: {path_str} is not a directory or YAML file — skipping",
                file=sys.stderr,
            )

    if not yaml_files:
        print("No YAML test spec files found.", file=sys.stderr)
        return 1

    # Summary counters
    counts: dict[str, int] = {
        "written": 0,
        "skipped": 0,
        "dry_run": 0,
        "no_template": 0,
        "no_test_file": 0,
        "error": 0,
    }

    _print_banner("═")
    mode = "DRY RUN — no files written" if args.dry_run else "GENERATE TEST STUBS"
    print(f"  {mode}")
    print(f"  Repo root: {repo_root}")
    print(f"  Processing {len(yaml_files)} YAML spec file(s)")
    _print_banner("═")

    for yaml_path in yaml_files:
        status, message = process_spec_file(
            yaml_path,
            repo_root=repo_root,
            dry_run=args.dry_run,
            force=args.force,
        )
        counts[status] += 1
        prefix = {
            "written": "  ✓",
            "skipped": "  →",
            "dry_run": "  ~",
            "no_template": "  ·",
            "no_test_file": "  ·",
            "error": "  ✗",
        }.get(status, "  ?")
        print(f"{prefix}  [{yaml_path.name}]  {message}")

    _print_banner()
    print(
        f"  Written: {counts['written']}  |  "
        f"Skipped (exists): {counts['skipped']}  |  "
        f"No template: {counts['no_template']}  |  "
        f"Errors: {counts['error']}"
    )
    if args.dry_run:
        print("  (dry run — re-run without --dry-run to write files)")
    _print_banner("═")

    return 0 if counts["error"] == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
